// <auto-generated />
using System;
using ClientSideInterface.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientSideInterface.Migrations
{
    [DbContext(typeof(GamesContext))]
    partial class GamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClientSideInterface.Models.GamesModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("systemModelSystemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("systemModelSystemID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Genere = "Sport",
                            Rating = "E",
                            SystemID = 1,
                            Title = "Mario Kart 8"
                        },
                        new
                        {
                            ID = 2,
                            Genere = "Action",
                            Rating = "M",
                            SystemID = 2,
                            Title = "Halo"
                        },
                        new
                        {
                            ID = 3,
                            Genere = "Casual",
                            Rating = "E",
                            SystemID = 3,
                            Title = "Candy Crush"
                        },
                        new
                        {
                            ID = 4,
                            Genere = "Simulation",
                            Rating = "E",
                            SystemID = 4,
                            Title = "Microsoft Flight Simulatior"
                        },
                        new
                        {
                            ID = 5,
                            Genere = "Role-Playing",
                            Rating = "M",
                            SystemID = 5,
                            Title = "Assasins Creed"
                        },
                        new
                        {
                            ID = 6,
                            Genere = "Strategy",
                            Rating = "E 10+",
                            SystemID = 4,
                            Title = "Civilization"
                        },
                        new
                        {
                            ID = 7,
                            Genere = "Action",
                            Rating = "M",
                            SystemID = 5,
                            Title = "Far Cry 6"
                        },
                        new
                        {
                            ID = 8,
                            Genere = "Action",
                            Rating = "M",
                            SystemID = 4,
                            Title = "Back 4 Blood"
                        },
                        new
                        {
                            ID = 9,
                            Genere = "Casual",
                            Rating = "E",
                            SystemID = 4,
                            Title = "Minecraft"
                        },
                        new
                        {
                            ID = 10,
                            Genere = "Casual",
                            Rating = "E",
                            SystemID = 1,
                            Title = "Super Mario Party"
                        },
                        new
                        {
                            ID = 11,
                            Genere = "Role-Playing",
                            Rating = "M",
                            SystemID = 2,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            ID = 12,
                            Genere = "Role-Playing",
                            Rating = "M",
                            SystemID = 4,
                            Title = "Fallout: New Vegas"
                        },
                        new
                        {
                            ID = 13,
                            Genere = "Simulation",
                            Rating = "E",
                            SystemID = 4,
                            Title = "Cities: Skylines"
                        },
                        new
                        {
                            ID = 14,
                            Genere = "Simulation",
                            Rating = "E",
                            SystemID = 4,
                            Title = "Kerbal Space Program"
                        },
                        new
                        {
                            ID = 15,
                            Genere = "Sport",
                            Rating = "E",
                            SystemID = 2,
                            Title = "FIFA 21"
                        },
                        new
                        {
                            ID = 16,
                            Genere = "Sport",
                            Rating = "E",
                            SystemID = 5,
                            Title = "NBA 2K21"
                        },
                        new
                        {
                            ID = 17,
                            Genere = "Strategy",
                            Rating = "T",
                            SystemID = 4,
                            Title = "Europa Universalis 4"
                        },
                        new
                        {
                            ID = 18,
                            Genere = "Strategy",
                            Rating = "T",
                            SystemID = 4,
                            Title = "Sins of a Solar Empire"
                        });
                });

            modelBuilder.Entity("ClientSideInterface.Models.SystemModel", b =>
                {
                    b.Property<int>("SystemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemID");

                    b.ToTable("System");

                    b.HasData(
                        new
                        {
                            SystemID = 1,
                            Brand = "Nintendo",
                            Name = "Switch"
                        },
                        new
                        {
                            SystemID = 2,
                            Brand = "Microsoft",
                            Name = "XBox"
                        },
                        new
                        {
                            SystemID = 3,
                            Brand = "Apple",
                            Name = "IOS"
                        },
                        new
                        {
                            SystemID = 4,
                            Brand = "Microsoft",
                            Name = "Windows"
                        },
                        new
                        {
                            SystemID = 5,
                            Brand = "Sony",
                            Name = "Playstation"
                        });
                });

            modelBuilder.Entity("ClientSideInterface.Models.GamesModel", b =>
                {
                    b.HasOne("ClientSideInterface.Models.SystemModel", "systemModel")
                        .WithMany()
                        .HasForeignKey("systemModelSystemID");

                    b.Navigation("systemModel");
                });
#pragma warning restore 612, 618
        }
    }
}
